### ISSUE TITLE
Version of Numpy and CasADi?

### ISSUE THREAD

**Issue by Mrzhang-hub** [saehong/RL-BATT-DDPG#1]
I met the following problem when I run this code,

```
  File "D:\Anaconda38\envs\Transformer\lib\site-packages\casadi\casadi.py", line 9209, in __array__
    return self.full()
  File "D:\Anaconda38\envs\Transformer\lib\site-packages\casadi\casadi.py", line 7977, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, SX, name)
  File "D:\Anaconda38\envs\Transformer\lib\site-packages\casadi\casadi.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'SX' object has no attribute 'full'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "E:\PycCharm2021\PyCharm 2021.1.1\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\PycCharm2021\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/RL-BATT-DDPG-main/RL-BATT-DDPG-main/OutputFeedback_RL/main_training_testing_output_fdbk.py", line 272, in <module>
    env = DFN(sett=settings, cont_sett=control_settings)
  File "D:\RL-BATT-DDPG-main\RL-BATT-DDPG-main\OutputFeedback_RL\gym_dfn\envs\dfn_env.py", line 189, in __init__
    self.x_dot, self.g_, self.L, self.x_outs, self.z_outs, self.info_outs, self.param_outs, self.debug_outs = dae_dfn_casadi_pade(self.x,self.z,self.u,p)
  File "D:\RL-BATT-DDPG-main\RL-BATT-DDPG-main\OutputFeedback_RL\gym_dfn\envs\DFN_Utils.py", line 88, in dae_dfn_casadi_pade
    A_csn, B_csn, A_csp, B_csp, C_csn, C_csp = c_s_mats(p)
  File "D:\RL-BATT-DDPG-main\RL-BATT-DDPG-main\OutputFeedback_RL\gym_dfn\envs\DFN_Utils.py", line 356, in c_s_mats
    b_vecn = symsubsnum(p['R_s_n'],p['D_s_n'])
  File "D:\RL-BATT-DDPG-main\RL-BATT-DDPG-main\OutputFeedback_RL\gym_dfn\envs\DFN_Utils.py", line 462, in symsubsnum
    n = np.array([[-3.0/R],[-(4.0*R)/(11.0*D)],[-(R**(3))/(165*(D**(2)))]])
  File "D:\Dyang_Research\Anaconda38\envs\Transformer\lib\site-packages\casadi\casadi.py", line 9211, in __array__
    raise Exception("Implicit conversion of symbolic CasADi type to numeric matrix not supported.\n"
Exception: Implicit conversion of symbolic CasADi type to numeric matrix not supported.
This may occur when you pass a CasADi object to a numpy function.
Use an equivalent CasADi function instead of that numpy function.
python-BaseException
```

I guess it is caused by the version incompatibility of Numpy and CasADi. So I want to ask what's the version of these two packages you used when running this code?  (my Numpy version is 1.23.4 and CasADi is 3.5.5)

**Comment by limpid-11** [comment]
@Mrzhang-hub Has this problem been solved, please? I had the same question.
